services:
    paymentservice:
        build:
            context: .
            dockerfile: PaymentService/Dockerfile
        container_name: paymentservice
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - APP_UID=1000
        ports:
            - "5000:8080"
        networks:
            - backend

    tokenservice:
        build:
            context: .
            dockerfile: TokenService/Dockerfile
        container_name: tokenservice
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - APP_UID=1000
        ports:
            - "5001:8080"
        networks:
            - backend

    transactionlogservice:
        build:
            context: .
            dockerfile: TransactionLogService/Dockerfile
        container_name: transactionlogservice
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - APP_UID=1000
        ports:
            - "5002:8080"
        networks:
            - backend

    walletservice:
        build:
            context: .
            dockerfile: WalletService/Dockerfile
        container_name: walletservice
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - APP_UID=1000
        ports:
            - "5003:8080"
        networks:
            - backend

networks:
    backend:
        driver: bridge