apiVersion: apps/v1
kind: Deployment
metadata:
    name: paymentservice
    labels:
        app: paymentservice
spec:
    replicas: 1
    selector:
        matchLabels:
            app: paymentservice
    template:
        metadata:
            labels:
                app: paymentservice
        spec:
            containers:
                - name: paymentservice
                  image: paymentservice:latest
                  ports:
                    - containerPort: 8080
                  env:
                    - name: ASPNETCORE_ENVIRONMENT
                      value: "Development"
                    - name: APP_UID
                      value: "1000"